# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on:
  push:
    branches: [ "dev" ] #trigger on each push to dev
  pull_request:
    branches: [ "dev" ] #trigger on each PR for dev

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
#    - name: Build
#      run: swift build -v
#    - name: Run tests
#      run: swift test -v
    - uses: actions/cache@v2
      with:
        path: Pods
        key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-pods-
    - name: CocoaPod Install
      run: pod install
    - name: Build
      run: xcodebuild clean build test -workspace actionsDemo.xcworkspace -scheme actionsDemo -sdk iphonesimulator -destination "platform=iOS Simulator" ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO
    - name: Test
      run: xcodebuild -workspace actionsDemo.xcworkspace -scheme actionsDemo -sdk iphonesimulator -destination 'platform:iOS Simulator, id:dvtdevice-DVTiOSDeviceSimulatorPlaceholder-iphonesimulator:placeholder, name:Any iOS Simulator Device' test
